config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments
    resource :like
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @post.likes.where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_likes.html.erb
<% if user_signed_in? && current_user.likes?(post) %>
    <%= link_to post_like_path(post), method: :delete, remote: true do%>
        <span class="glyphicon glyphicon-thumbs-down"></span> 悪い！
    <% end %>
<% else %>
    <%= link_to post_like_path(post), method: :post, remote: true do%>
        <span class="glyphicon glyphicon-thumbs-up"></span> いいね！
    <% end %>
<% end %>
<br>
<%= post.likes.count %>

app/views/likes/create.js.erb
$("#post_<%= @post.id %>_likes").html("<%=j render partial: "likes", locals: {post: @post} %>");

app/views/likes/destroy.js.erb
$("#post_<%= @post.id %>_likes").html("<%=j render partial: "likes", locals: {post: @post} %>");
$('#comment_content_<%= @post.id %>').val('')