config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'
  resources :posts do
    resources :comments
    resource :like
  end
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile
end

app/models/post.rb
class Post < ApplicationRecord
  validates :image, presence: true
  validates :user_id, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC').page(params[:page]).per(5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :caption)
    end

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: { multipart: true } do |f| %>
            <div class="row">
              <div class="col-md-12 text-center">
                <%= f.error_notification %>
              </div>
            </div>
            <div class="container-fluid">
              <div class="form-group text-center">
                <h4 class="col-md-4">Upload an image:</h4>
                <%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)', class: 'col-md-8' } %>
              </div>
              <div class="form-group text-center">
                <%= f.input :caption, label: false, placeholder: 'Add your caption', input_html: { class: 'input-caption'} %>
              </div>
              <div class="form-group text-center">
                <%= f.button :submit, class: 'btn-success btn-block' %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
      <div class="time-ago">
        <%= time_ago_in_words post.created_at %>
      </div>
      <div class="caption">
        <%= post.caption %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="comments" id="comments_<%= post.id %>">
        <% if post.comments.any? %>
            <div class="paginator" id="#comments-paginator-<%= post.id %>">
              <% unless post.comments.count <= 4 %>
                  <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"} %>
              <% end %>
            </div>
            <%= render post.comments.last(4), post: post %>
        <% end %>
      </div>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-2">
        <div id="post_<%= post.id %>_likes">
          <%= render "likes/likes", post: post %>
        </div>
      </div>
      <div class="comment-form col-sm-10">
        <%= form_for [post, post.comments.new], remote: true do |f| %>
            <%= f.text_field :content, placeholder: 'コメントする' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        // =link_to post.user.user_name, profile_path(post.user.user_name)?
      .time-ago
        =time_ago_in_words post.created_at
    .image.center-block
      =link_to (image_tag post.image.url(:medium), class:'img-responsive'),
                 post_path(post)
    .post-bottom
      = render 'posts/likes', post: post
      .caption
        .caption-content
          .user-name
            // =link_to post.user.user_name, profile_path(post.user.user_name)
          =post.caption
          .comments{id: "comments_#{post.id}"}
            -if post.comments.any?
              = render post.comments.first(4), post: post
              -unless post.comments.count <= 4
                .paginator{id: "#comments-paginator-#{post.id}"}
                  =link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data: {post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"}
    .comment-like-form.row
      .col-sm-1.like-button
        =link_to '', like_post_path(post.id), remote: true,
                                              id: "like_#{post.id}",
                                              class: "like glyphicon #{liked_post post}"
      .comment-form.col-sm-11
        =form_for([post, post.comments.build], remote: true) do |f|
          =f.text_field :content, placeholder: 'Add a comment...',
                                   class: "comment_content",
                                   id: "comment_content_#{post.id}",
                                   data: { post_id: "#{post.id}",
                                   value: "#{post.comments.count}" }
          =f.submit 'New Comment', class: 'comment-submit-button' # Hidden with CSS

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <%= render 'post', post: post %>
<% end %>

app/views/posts/create.html.erb
<h1>OrderCombos#create</h1>
<p>Find me in app/views/order_combos/create.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form' %>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/edit.html.haml
.text-center
  = image_tag @post.image.url(:medium)
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :caption
    .form-group.text-center
      = f.button :submit, class: 'btn-success'
    .text-center.edit-links
      = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
      |
      = link_to "cancel", posts_path

app/views/posts/index.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'MORE POSTS', remote: true, id: 'load_more' %>
</div>

app/views/posts/index.html.haml
.posts-wrapper.row
  -@posts.each do |post|
    .post
      .post-head
        .name
          Lê Phúc
      .image.center-block
        =link_to (image_tag post.image.url(:medium), class:'img-responsive center-block'), post_path(post)
      %p.caption
        =post.caption

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.html.haml
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :caption
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <%= render 'post', post: @post %>
    <div class="text-center">
      <% if @post.user.id == current_user.id %>
        <%= link_to 'Edit', edit_post_path(@post) %> |
        <%= link_to 'Back', posts_path %>
      <% else %>
        <%= link_to 'Back', posts_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.haml
.posts-wrapper.row
  .post
    .post-head
      .name
        Ben Walker
    .image.center-block
      =image_tag @post.image.url(:medium), class:'img-responsive center-block'
    %p.caption
      =@post.caption
    .text-center
      .text-center.edit-links
        = link_to "Cancel", posts_path
        |
        = link_to "Edit Post", edit_post_path(@post)